apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-user
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-user-binding
subjects:
- kind: ServiceAccount
  name: pod-user
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-viewer
  apiGroup: rbac.authorization.k8s.io
