apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-vol-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: node-storage-class-1
  hostPath:
    path: /mnt
